services:
  nginx:
    container_name: '${CONTAINER_PREFIX_NAME}-nginx'
    image: nginx:1.21
    ports:
      - '80:80'
    env_file:
      - .env
    volumes:
      # vhost
      - ./nginx/templates/symfony.conf.template:/etc/nginx/templates/symfony.conf.template
      # code
      - ../app:/var/www/symfony
      # logs
      - ./nginx/logs:/var/log/nginx:cached
    networks:
      - app-network
    depends_on:
      - php

  php:
    container_name: '${CONTAINER_PREFIX_NAME}-php'
    build:
      context: ./php
    expose:
      - '9000'
    volumes:
      # code
      - ../app:/var/www/symfony
      # xdebug
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - app-network

  postgres:
    container_name: '${CONTAINER_PREFIX_NAME}-postgres'
    image: postgres:16.3
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
